name: Ping Vercel API Every 1 Minutes

on:
  schedule:
    - cron: '*/1 * * * *'  # Isso executa o job a cada 5 minutos
  workflow_dispatch:  # Isso permite que você execute manualmente o workflow se necessário

jobs:
  ping:
    runs-on: ubuntu-latest  # Executar no ambiente Ubuntu mais recente
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Faz o checkout do repositório

      - name: Make request to Vercel API
        run: |
          curl -X GET https://drink-bar.vercel.app//api/drink  # Substitua pela URL da sua API
